version: "3"
services:
  nextjs:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - nodemodules:/app/node_modules
      - build:/app/.next
    ports:
      - "1359:3000"
volumes:
  build: {}
  nodemodules: {}
